# Core application configuration
spring:
  application:
    name: farrin
  
  # Database configuration - H2 for testing
  datasource:
    url: jdbc:h2:mem:farrin
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  
  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true
    open-in-view: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        enable_lazy_loading_no_trans: true
    
  # Data JPA configuration
  data:
    jpa:
      repositories:
        enabled: true
  
  # Security Configuration
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN
  
  # Allow bean definition overriding
  main:
    allow-bean-definition-overriding: true
  
  # Jackson configuration to handle Hibernate proxies
  jackson:
    serialization:
      fail-on-empty-beans: false
    properties:
      hibernate-lazy-loading: true

# Server configuration
server:
  port: 8081

# Farrin application specific configuration
farrin:
  ml:
    service:
      url: ${FARRIN_ML_SERVICE_URL:http://localhost:5001}

# Logging configuration
logging:
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      farrin:
        farrin: DEBUG